### ISSUE TITLE
Improve documentation about usage

### ISSUE THREAD

**Issue by emartynov** [jraska/modules-graph-assert#35]
I tried to use plugin and  on the first run I get:

```
Execution failed for task ':assertMaxHeight'.
> Key root  tivi is missing in the map.
```

I don't understand what it means - do I miss the module declaration in layers or I exceed the max heigh?

**Comment by emartynov** [comment]
Oke, looking to the examples I see that I should apply it not in the root but in the app module. That removes that error and I can proceed further.

**Comment by emartynov** [comment]
This is also mentioned in the documentation - so I just a quick and impassioned reader. Sorry!

Closing for now.

**Comment by jraska** [comment]
Hey, thanks for using the plugin. It may not be clear on the first read so I just added one more sentence at the beginning of the usage section #36 to make it clearer.

Just in case you have any more ideas for the plugin, let me know.

Btw I like your profile description and I face a similar challenge, since mobile industry is still quite immature.

**Comment by emartynov** [comment]
I should definitely rewrite  - it was my core values 5 years ago :) 
As for now, this sentence is quite outdated and I have new values that I care about also.

**Comment by jraska** [comment]
Ok, when it comes to me I still think we have still some work to do to bring mobile development to the levels of backend development. 

I'm now working on some build time improvements and if I tell this to backend engineers, they look at me like I'm crazy and why we actually care about build times, because this problem is not so common in backend and if it exists, the cause is usually problematic design, not the tooling.

**Comment by emartynov** [comment]
That is true and the community is also looking to resolve it.

I wonder if you on any slack so we can continue the conversation there and flood this topic :)
