### ISSUE TITLE
Allow same layer dependencies

### ISSUE THREAD

**Issue by marcellogalhardo** [jraska/modules-graph-assert#59]
I'm studying how to integrate this library in my current project but I have a use case which I believe isn't covered today and/or the docs doesn't explain very well how to do it. Basically, I have a collection of nested modules that lives within same layer but they can depend upon each other. For example: `:network:core`, `:network:rx2`, `:network:coroutines`, `:network:testing`, etc.

The problem I face is: all these modules depends upon core and they should live together in the same layer/package. This happens in all "layers" and it is very important for us due to module cohesion, as we have hundreds of modules.

I'd like to know if is possible to **disable the validation within same layer** for all layers but still block any dependency between modules from different layers in the wrong direction.

For example, the following layers:
- features
- libraries
- base

Explanation: we could have N modules inside libraries that depends upon each other but they cannot depend on feature libraries, still respecting the max height defined in the enumerated layers.

Thank you in advance.

**Comment by jraska** [comment]
Hi Marcello, thank you for using the plugin and raising the issue. Sorry for the late reply.

For now we explicitly do not allow dependencies within same layer here - [LayersOrderAssert.kt](https://github.com/jraska/modules-graph-assert/blob/master/plugin/src/main/kotlin/com/jraska/module/graph/assertion/LayersOrderAssert.kt#L48)

However I think there are some options:

1. In case you have only 3 layers, it could be reasonable to use explicit restrictions instead of the layer concept and do something like: 
```
  restricted = [':libraries:\\S -X> :features:\\S', ':base:\\S -X> :features:\\S', ':base:\\S -X> :libraries:\\S']
``` 
The number of needed entries will grow fast if there is more layers, but it is doable with current plugin.

2. You can also use 
```
moduleLayersExclude = [":features:\\S* -> features:\\S*"]
``` 
to ignore these errors within same layer. Here it can be actually done by one regex for all layers using a group and relying on the fact we have the same prefix within the two colons:
```
moduleLayersExclude = [":(\\S*):\\S* -> :\\1:\\S*"]
```

3. Adding a switch to allow dependencies within layers into [LayersOrderAssert.kt](https://github.com/jraska/modules-graph-assert/blob/master/plugin/src/main/kotlin/com/jraska/module/graph/assertion/LayersOrderAssert.kt#L48). Could be a small bit of complexity for this use case and would mean adding a configuration `allowInLayerDependencies == true/false(default for backwards compatibility)`


Separate topic is the max height - currently this is calculated [from the dependency tree](https://github.com/jraska/modules-graph-assert/blob/master/plugin/src/main/kotlin/com/jraska/module/graph/assertion/ModuleTreeHeightAssert.kt) of the module and the layers are not in play here so any change in the layer ordering will not affect this.
However I think it is not a problem - the `layerIndex` and the module height are two independent values.



Please let me know if that makes sense and if option 1. or 2. can work for you now? The option 3 is doable, but maybe we don't need it.

Thanks

**Comment by marcellogalhardo** [comment]
Hi Josef! Thanks for your detailed answer.

I believe option 2 fulfill our use case, and I really like I can keep the "modulesLayer" which keep explicit the relationship between each layer.

I'm out of the office until next week but when I get back I will give a try to check if I will run in any unexpected issue - I will get back to you / close this issue as fast as possible.

Thanks a lot for your detailed answer!

**Comment by marcellogalhardo** [comment]
It worked as expected, thanks @jraska.

**Comment by jraska** [comment]
Thank you! :)
