### ISSUE TITLE
Bug: Key root  PROJECT_NAME is missing in the map.

### ISSUE THREAD

**Issue by marcellogalhardo** [jraska/modules-graph-assert#60]
When testing the library I'm facing the following error that doesn't allow me to execute `./gradlew assertModuleGraph`:

```
* What went wrong:
Execution failed for task ':assertMaxHeight'.
> Key root  PROJECT_NAME is missing in the map.
```

My assertion configuration is:

```
moduleGraphAssert {
    maxHeight = 14
    moduleLayers = [":features:\\S*", ":libraries\\S*", ":core\\S*"]
    moduleLayersExclude = [":(\\S*):\\S* -> :\\1:\\S*"]
}
```

**Comment by jraska** [comment]
Hey Marcello, thanks for reporting this. I reproduced the issue.

The bug is occurring only when the plugin is applied on the root project. To achieve the desired functionality please apply the plugin on the `:app` module - [Example project](https://github.com/jraska/github-client/blob/master/app/build.gradle#L143).

I will fix this, because we shouldn't crash in such case, however I beloieve you shouldn't be blocked by this is the plugin is applied on the module with the applciation? 

Thanks

**Comment by jraska** [comment]
Please give it a try with: https://github.com/jraska/modules-graph-assert/releases/tag/1.3.2, the height on root project should work as expected - asserting height of complete module graph.

Thanks again for the report :)

**Comment by marcellogalhardo** [comment]
Hey @jraska !

It is working as expected in version 1.3.2.

Thanks a lot. ✌️
