### ISSUE TITLE
[Feature Request] Extract statistics for machine readable format

### ISSUE THREAD

**Issue by marcellogalhardo** [jraska/modules-graph-assert#77]
This issue is a follow up of: https://github.com/jraska/modules-graph-assert/issues/64#issuecomment-675031140

The concept would be to introduce a new Gradle task that export the project graph statistics in a machine readable format that can be used by CI pipelines to keep track on how a given project is growing. 

For an initial implementation, we would use the output of `modulesGraphPrintStatististics` and extract it a simple format (probably by an agnostic printer so we can add support to other formats in future).

Later, we should consider a more fine grained data output: for example, per module get the longest path. Rationality: we could create a report that show us which module is growing in which direction. Risk: we should identify how fast this would be in huge projects.

@jraska let me know what do you think.

**Comment by jraska** [comment]
Hi @marcellogalhardo , thanks a lot for the feedback and inputs :)

What I think is that statistics you mention are interesting and I had a few other discussions about what could be measured and reported. The challenging part is picking the right one because each project might want to trace different things with different actionability of these metrics.

Also for me it is important to focus on the purpose of this plugin, which is asserting the module graph. The statistics and graph painting are just simple helper features, which might be a separate plugin at the end. 
This is also a reason why I'm a bit reluctant to start investing into these directions as my concern is that we could go really far with complexity there and my opinion is I really want to keep the scope small and simple, otherwise I wouldn't be able to maintain the project in a long term. 
One direction I'm also exploring is mentioned here: #73 


So as an answer I can imagine a PR adding a simple JSON printing for existing statistics, but behind that simplicity is publishing a JSON and API contract for plugin consumers and maintaining that.
At the same time as you mention this s probably not enough and more data per module could be reported, My thinking here is this could be a plugin within your project not relying on a third party, which is what we did in my company as well, because than you can effectively report the data you want to action on anywhere you want without any contract maintenance.

Please let me know if my thoughts make sense to you. I'm happy to discuss what else could be measured for healthy dependency graph.

**Comment by marcellogalhardo** [comment]
Hey @jraska - after thinking a lot about your comment I agree with you. After analysing how we are using in my company: our main use case is to validate the graph structure and block PRs automatically when violations are found.

The basic statistics are nice to have but to add more complex reports we would need to add a big overall complexity in the library which doesn't make sense and as you pointed out: it is not the main goal of the library. On the mean time I saw #73 and looks like the right direction this library should go and matches our main use case.

Thanks a lot for the detailed answer.

**Comment by jraska** [comment]
Hey @marcellogalhardo . Thanks a lot for thinking about it and understanding :)

If you have a moment any time I would be more curious on how exactly you use it in your company? Are the rules you mentioned in #79  in place and this is running on your CI?

Which statistics you would find relevant? The longest path of each module or some other graph property? 

Thanks a for any answer as I find this interesting to understand better how other people would use such kind of data.

**Comment by marcellogalhardo** [comment]
Hey @jraska - sorry for the super late reply.

Yes, we have a set of custom rules that are running in the CI in the check step and we are slowly moving our modules to that structure. In total we have 230+ modules but only a subset of them are validated, around 55 libraries and 23 features.

Today the information that mostly interest us are:
- The total height of the Main App;
- The total height of Feature Apps (these are app modules that includes only a specific feature);
- The validation of the relationship between layers: we have around 30 Android Devs and it is easier to lose track of how the Gradle Graph is evolving.

**Comment by jraska** [comment]
Hey @marcellogalhardo, thanks a lot for sharing those insights! 👍 

The information you mentioned about the Feature Apps can be actually enforced by applying the `module-graph-assert` plugin on their module. :)

Regarding the custom rules, I would be quite interested in that. We have similar size of the Android devs, 80 modules with few "module types" and enforced module types rules, running on each build for early feedback. Like Implementation module cannot depend on another implementation module etc.
We also did some PoCs on the Feature Apps so another very common problem we try to solve.


**My Proposal:**
To me any discussion on these topics would be very interesting, because I feel like our companies are tackling the same challenges. Would you be open to a conversation on these topics? I would be happy to jump on a call once there is a room for it. 
Or another option could be some virtual meetup if we find any. As such conversation would normally happen on some conference.
Let me know what you think, Thanks :)

**Comment by marcellogalhardo** [comment]
Hey @jraska - your idea of a call to share use cases sounds great for me.

I will contact you in a private way so we can organize it. 😄
