### ISSUE TITLE
Please change the dependency coordinates

### ISSUE THREAD

**Issue by ZacSweers** [jraska/modules-graph-assert#91]
The current dependency coordinates are `gradle.plugin.project:plugin:1.4.0`, which I believe must be an accident. I would expect this project to use the canonical reverse-domain declaration format like `com.jraska.modulesgraphassert` or similar. This coordinate also looks highly suspect to consumers.

**Comment by jraska** [comment]
Hi @ZacSweers, thanks for raising this.

I'm aware of that and I was investigating some time ago why - without success. 
When publishing the plugin based on the [Gradle Guide](https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html) all the fields are there and I would assume the [plugin id](https://github.com/jraska/modules-graph-assert/blob/master/plugin/build.gradle#L36) should be picked up the Gradle publish plugin, however this is case only for the id to the plugin and not the coordinates as you raise.

Because the `plugins {  id "com.jraska.module.graph.assertion")... }` format is correct and it is [the one Gradle recommends ](https://docs.gradle.org/current/userguide/plugins.html )and uses in their docs, I didn't put more effort into the investigation of the coordinates format and causes of that inconsistency.

I would be happy for suggestions, because it will be probably one liner _somewhere_ to fix this.

**Comment by runningcode** [comment]
We would like to help you take care of this. Please submit a help request via https://plugins.gradle.org/docs/get-help so this can get routed to the appropriate team.

**Comment by jraska** [comment]
@runningcode please I submitted a help request, but didn't hear back yet :)

**Comment by donat** [comment]
I'll respond soon.

**Comment by jraska** [comment]
Waiting for Gradle plugin approval now - [group set](https://github.com/jraska/modules-graph-assert/pull/99/files#diff-520f178549fabd7e74f5b1fedb7275a1434a2ac153fc49e0212455ceeef38e37R33) as suggested by Gradle engineers - let's see if it fixed the issue.

**Comment by jraska** [comment]
This is solved now. The coordinates are now: `"com.jraska.module.graph.assertion:plugin:1.5.0"`

Thanks for raising it. :)

**Comment by ZacSweers** [comment]
Thanks!
